console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  base = '#1e1e2e'
  black = '#45475A'
  blue = '#89b4fa'
  closer = '#ACB0BE'
  crust = '#11111b'
  cyan = '#94E2D5'
  flamigo = '#f2cdcd'
  green = '#A6E3A1'
  lavender = '#b4befe'
  magenta = '#F5C2E7'
  mantle = '#181825'
  maroon = '#eba0ac'
  mauve = '#cba6f7'
  orange = '#fab387'
  os = '#ACB0BE'
  overlay0 = '#6c7086'
  overlay1 = '#7f849c'
  overlay2 = '#9399b2'
  peach = '#fab387'
  pink = '#f5c2e7'
  purple = '#cba6f7'
  red = '#F38BA8'
  rosewater = '#f5e0dc'
  sapphire = '#74c7ec'
  sky = '#89dceb'
  subtext0 = '#a6adc8'
  subtext1 = '#bac2de'
  surface0 = '#313244'
  surface1 = '#45475a'
  surface2 = '#585b70'
  teal = '#94e2d5'
  text = '#cdd6f4'
  white = '#BAC2DE'
  yellow = '#F9E2AF'

[secondary_prompt]
  template = ' '
  foreground = 'p:closer'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{.Icon}} '
    foreground = 'p:flamigo'
    type = 'os'
    style = 'plain'

  [[blocks.segments]]
    template = ' '
    foreground = 'p:blue'
    type = 'root'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ if .SSHSession }} {{ end }}{{ .UserName }} '
    foreground = 'p:blue'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ path .Path .Location }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '{{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:mauve'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      branch_max_length = 25
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    template = '   {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'
    foreground = 'p:green'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      fetch_package_manager = true
      npm_icon = ' <p:green></>'
      yarn_icon = ' <p:green></>'

  [[blocks.segments]]
    template = '   {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
    foreground = 'p:yellow'
    type = 'python'
    style = 'plain'

  [[blocks.segments]]
    template = '   {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = 'p:magenta'
    type = 'java'
    style = 'plain'

  [[blocks.segments]]
    template = '   {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = 'p:sky'
    type = 'go'
    style = 'diamond'

  [[blocks.segments]]
    template = '   {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = 'p:maroon'
    type = 'rust'
    style = 'plain'

  [[blocks.segments]]
    template = '   {{.Context}}'
    foreground = 'p:sapphire'
    type = 'docker'
    style = 'plain'

  [[blocks.segments]]
    template = '   {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}'
    foreground = 'p:blue'
    type = 'kubectl'
    style = 'plain'

  [[blocks.segments]]
    template = '   {{ .CurrentDate | date "3:04:05 PM"}}'
    foreground = 'p:lavender'
    type = 'time'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' '
    foreground = 'p:subtext1'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true

[[tooltips]]
  template = '   {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }}'
  foreground = 'p:peach'
  type = 'aws'
  style = 'plain'
  tips = ['aws']

[[tooltips]]
  template = '   {{ .Name }}'
  foreground = 'p:peach'
  type = 'az'
  style = 'plain'
  tips = ['az']

[[tooltips]]
  template = '   {{ .Project }}'
  foreground = 'p:peach'
  type = 'gcp'
  style = 'plain'
  tips = ['gcp']

[[tooltips]]
  template = '   {{ .Stack }}{{if .User }} :: {{ .User }}@{{ end }}{{ if .URL }}{{ .URL }}{{ end }}'
  foreground = 'p:sapphire'
  type = 'pulumi'
  style = 'plain'
  tips = ['pulumi']
